fix inde.html verification

diff --git a/.github/workflows/azure-static-web-apps-witty-rock-06108e103.yml b/.github/workflows/azure-static-web-apps-witty-rock-06108e103.yml
--- a/.github/workflows/azure-static-web-apps-witty-rock-06108e103.yml
+++ b/.github/workflows/azure-static-web-apps-witty-rock-06108e103.yml
@@ -33,13 +33,7 @@ jobs:
                return await coredemo.getIDToken()
            result-encoding: string
       - name: Vérifier la présence de index.html
-        run: |
-          if [ -f ./frontend/index.html ]; then
-            echo "File exists"
-          else
-            echo "File missing"
-            exit 
-          fi 
+        run: test -f ./src/frontend/index.html || (echo "File missing" && exit 1)
       - name: Build And Deploy
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v1
