C/CD V1.2.1 Test to just fix backend workflow

diff --git a/.github/workflows/azure-static-web-apps-witty-rock-06108e103.yml b/.github/workflows/azure-static-web-apps-witty-rock-06108e103.yml
--- a/.github/workflows/azure-static-web-apps-witty-rock-06108e103.yml
+++ b/.github/workflows/azure-static-web-apps-witty-rock-06108e103.yml
@@ -1,108 +1,108 @@
-name: Azure Static Web Apps CI/CD
+# name: Azure Static Web Apps CI/CD
 
-on:
-  push:
-    branches:
-      - frontend
-  pull_request:
-    types: [opened, synchronize, reopened, closed]
-    branches:
-      - frontend
+# on:
+#   push:
+#     branches:
+#       - frontend
+#   pull_request:
+#     types: [opened, synchronize, reopened, closed]
+#     branches:
+#       - frontend
 
-jobs:
-  build_and_deploy_job:
-    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
-    runs-on: ubuntu-latest
-    name: Build and Deploy Job
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          submodules: true
-          lfs: false
-      - name: Install OIDC Client from Core Package
-        run: npm install @actions/core@1.6.0 @actions/http-client
-      - name: Get Id Token
-        uses: actions/github-script@v6
-        id: idtoken
-        with:
-          script: |
-            const coredemo = require('@actions/core')
-            return await coredemo.getIDToken()
-          result-encoding: string
-      # - name: Vérifier la présence de index.html
-      #   run:
-      - name: Build And Deploy
-        id: builddeploy
-        uses: Azure/static-web-apps-deploy@v1
-        with:
-          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_ROCK_06108E103 }}
-          action: "upload"
-          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
-          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
-          app_location: "./src/frontend" # App source code path
-          api_location: "" # Api source code path - optional
-          output_location: "." # Built app content directory - optional
-          github_id_token: ${{ steps.idtoken.outputs.result }}
-          ###### End of Repository/Build Configurations ######
-  lighthouse_check:
-    needs: build_and_deploy_job
-    runs-on: ubuntu-latest
-    name: lighthouse test
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - uses: actions/checkout@v5
-      - name: Wait for deployment
-        run: |
-          for i in {1..12}; do
-            if curl -s -o /dev/null -w "%{http_code}" https://witty-rock-06108e103.6.azurestaticapps.net/ | grep 200; then
-              echo "Site ready!"
-              break
-            fi
-            echo "Waiting 5 seconds..."
-            sleep 5
-          done
-      - name: Audit URLs using Lighthouse
-        uses: treosh/lighthouse-ci-action@v12
-        with:
-          urls: |
-            https://witty-rock-06108e103.6.azurestaticapps.net/
-          configPath: ./lighthouserc.json
-  lighthouse_report:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v5
-      - name: Audit URLs using Lighthouse
-        uses: treosh/lighthouse-ci-action@v12
-        with:
-          urls: |
-            https://witty-rock-06108e103.6.azurestaticapps.net/
-          budgetPath: ./budget.json # test performance budgets
-          uploadArtifacts: true # save results as an action artifacts
-          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
-  check_for_index_file:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v5
-      - name: Check the presence of index.html
-        run: |
-          if [ -f ./src/frontend/index.html ]; then
-            echo "File exists"
-          else
-            echo "File missing"
-            exit 1
-          fi
-  close_pull_request_job:
-    if: github.event_name == 'pull_request' && github.event.action == 'closed'
-    runs-on: ubuntu-latest
-    name: Close Pull Request Job
-    steps:
-      - name: Close Pull Request
-        id: closepullrequest
-        uses: Azure/static-web-apps-deploy@v1
-        with:
-          action: "close"
+# jobs:
+#   build_and_deploy_job:
+#     if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
+#     runs-on: ubuntu-latest
+#     name: Build and Deploy Job
+#     permissions:
+#       id-token: write
+#       contents: read
+#     steps:
+#       - uses: actions/checkout@v3
+#         with:
+#           submodules: true
+#           lfs: false
+#       - name: Install OIDC Client from Core Package
+#         run: npm install @actions/core@1.6.0 @actions/http-client
+#       - name: Get Id Token
+#         uses: actions/github-script@v6
+#         id: idtoken
+#         with:
+#           script: |
+#             const coredemo = require('@actions/core')
+#             return await coredemo.getIDToken()
+#           result-encoding: string
+#       # - name: Vérifier la présence de index.html
+#       #   run:
+#       - name: Build And Deploy
+#         id: builddeploy
+#         uses: Azure/static-web-apps-deploy@v1
+#         with:
+#           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_ROCK_06108E103 }}
+#           action: "upload"
+#           ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
+#           # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
+#           app_location: "./src/frontend" # App source code path
+#           api_location: "" # Api source code path - optional
+#           output_location: "." # Built app content directory - optional
+#           github_id_token: ${{ steps.idtoken.outputs.result }}
+#           ###### End of Repository/Build Configurations ######
+#   lighthouse_check:
+#     needs: build_and_deploy_job
+#     runs-on: ubuntu-latest
+#     name: lighthouse test
+#     permissions:
+#       id-token: write
+#       contents: read
+#     steps:
+#       - uses: actions/checkout@v5
+#       - name: Wait for deployment
+#         run: |
+#           for i in {1..12}; do
+#             if curl -s -o /dev/null -w "%{http_code}" https://witty-rock-06108e103.6.azurestaticapps.net/ | grep 200; then
+#               echo "Site ready!"
+#               break
+#             fi
+#             echo "Waiting 5 seconds..."
+#             sleep 5
+#           done
+#       - name: Audit URLs using Lighthouse
+#         uses: treosh/lighthouse-ci-action@v12
+#         with:
+#           urls: |
+#             https://witty-rock-06108e103.6.azurestaticapps.net/
+#           configPath: ./lighthouserc.json
+#   lighthouse_report:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - uses: actions/checkout@v5
+#       - name: Audit URLs using Lighthouse
+#         uses: treosh/lighthouse-ci-action@v12
+#         with:
+#           urls: |
+#             https://witty-rock-06108e103.6.azurestaticapps.net/
+#           budgetPath: ./budget.json # test performance budgets
+#           uploadArtifacts: true # save results as an action artifacts
+#           temporaryPublicStorage: true # upload lighthouse report to the temporary storage
+#   check_for_index_file:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - uses: actions/checkout@v5
+#       - name: Check the presence of index.html
+#         run: |
+#           if [ -f ./src/frontend/index.html ]; then
+#             echo "File exists"
+#           else
+#             echo "File missing"
+#             exit 1
+#           fi
+#   close_pull_request_job:
+#     if: github.event_name == 'pull_request' && github.event.action == 'closed'
+#     runs-on: ubuntu-latest
+#     name: Close Pull Request Job
+#     steps:
+#       - name: Close Pull Request
+#         id: closepullrequest
+#         uses: Azure/static-web-apps-deploy@v1
+#         with:
+#           action: "close"
